### =========================
### TASK MANAGER API
### =========================


### 1. GET - Get all tasks
GET http://localhost:5037/api/Tasks
Accept: application/json


### 2. GET - Get task by ID
GET http://localhost:5037/api/Tasks/1
Accept: application/json


### 3. POST - Create a new task
POST http://localhost:5037/api/Tasks
Content-Type: application/json

{
  "title": "Learn JavaScript",
  "priority": "High",
  "isDone": false
}


### 4. PUT - Update a task
PUT http://localhost:5037/api/Tasks/5
Content-Type: application/json

{
  "title": "Learn ASP.NET Core",
  "priority": "Medium",
  "isDone": false
}


### 5. DELETE - Delete a task
DELETE http://localhost:5037/api/Tasks/1